version: '3.7'
services:
  sql-client:
    container_name: sql-client
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /opt/flink/bin/sql-client.sh
      - embedded
      - -l
      - /opt/sql-client/lib

      # uncomment to run the "Hello, Flink" pipeline from a file
      # - -f
      # - /etc/sql/hello_flink.sql

      # uncomment to run the "Trade Stats" pipeline from a file
      # - -f
      # - /etc/sql/trade_stats.sql

      # Note: if you don't uncomment one of the pipelines above,
      # you'll be dropped into a SQL client CLI. This is a great for
      # experimentation and pipeline development :)
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    volumes:
      - ./01-flink-intro/sql:/etc/sql
