# Used for Killercoda. Same as the other file, but we remove Redpanda Console
version: '3.7'
networks:
  master_class:
    driver: bridge
services:
  # Flink cluster
  jobmanager:
    container_name: jobmanager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - master_class
  taskmanager:
    container_name: taskmanager
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
    networks:
      - master_class
  sql-client:
    container_name: sql-client
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /opt/flink/bin/sql-client.sh
      - embedded
      - -l
      - /opt/sql-client/lib

      # uncomment to run the "Trade Stats" pipeline from a file
      - -f
      - /etc/sql/strategy-serverless.sql

      # Note: if you don't uncomment one of the pipelines above,
      # you'll be dropped into a SQL client CLI. This is a great for
      # experimentation and pipeline development :)
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    volumes:
      - ./03-strategy-testing/sql:/etc/sql
    networks:
      - master_class
